export const REQUEST_SAVE_USER_DATA = 'REQUEST_SAVE_USER_DATA';
export const USER_DATA_WAS_SAVED = 'USER_DATA_WAS_SAVED';
export const USER_DATA_WAS_NOT_SAVED = 'USER_DATA_WAS_NOT_SAVED';

export const CHECK_LOGIN = 'CHECK_LOGIN';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';

export const REQUEST_CLEAR_USER = 'REQUEST_CLEAR_USER';
export const USER_WAS_CLEARED = 'USER_WAS_CLEARED';
export const USER_WAS_NOT_CLEARED = 'USER_WAS_NOT_CLEARED';

export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';

export const REMOVE_ERROR = 'REMOVE_ERROR';
