export const REQUEST_SAVE_NEW_RATING = "REQUEST_SAVE_NEW_RATING"
export const NEW_RATING_WAS_SAVED = "NEW_RATING_WAS_SAVED"
export const NEW_RATING_WAS_NOT_SAVED = "NEW_RATING_WAS_NOT_SAVED"

export const REQUEST_RATINGS = "REQUEST_RATINGS"
export const RECEIVE_RATINGS = "RECEIVE_RATINGS"
export const REQUEST_RATINGS_FAILED = "REQUEST_RATINGS_FAILED"

export const REQUEST_DELETE_RATING = "REQUEST_DELETE_RATING"
export const RATING_WAS_DELETED = "RATING_WAS_DELETED"
export const RATING_WAS_NOT_DELETED = "RATING_WAS_NOT_DELETED"
