export const REQUEST_SAVE_NEW_TIP = "REQUEST_SAVE_NEW_TIP"
export const NEW_TIP_WAS_SAVED = "NEW_TIP_WAS_SAVED"
export const NEW_TIP_WAS_NOT_SAVED = "NEW_TIP_WAS_NOT_SAVED"

export const REQUEST_TIP = "REQUEST_TIP"
export const RECEIVE_TIP = "RECEIVE_TIP"
export const REQUEST_TIP_FAILED = "REQUEST_TIP_FAILED"

export const REQUEST_TIPS = "REQUEST_TIPS"
export const RECEIVE_TIPS = "RECEIVE_TIPS"
export const RECEIVE_TIPS_FAILED = "RECEIVE_TIPS_FAILED"

export const TIP_WAS_SAVED = "TIP_WAS_SAVED"
export const TIP_WAS_NOT_SAVED = "TIP_WAS_NOT_SAVED"
export const REQUEST_SAVE_TIP = "REQUEST_SAVE_TIP"

export const TIP_WAS_CREATED = "TIP_WAS_CREATED"
export const TIP_WAS_NOT_CREATED = "TIP_WAS_NOT_CREATED"
export const REQUEST_CREATE_TIP = "REQUEST_CREATE_TIP"

export const REQUEST_DELETE_TIP = "REQUEST_DELETE_TIP"

export const TIP_WAS_DELETED = "TIP_WAS_DELETED"

export const TIP_WAS_NOT_DELETED = "TIP_WAS_NOT_DELETED"
